export const generateIncidentReport = ({
  userName,
  sosId,
  startTime,
  endTime,
  district,
  locationHistory,
  riskScore,
  triggerType,
  trackingLink,
}) => {
  const durationMinutes = Math.round(
    (new Date(endTime) - new Date(startTime)) / 60000
  );

  const formatTime = (iso) =>
    new Date(iso).toLocaleString("en-BD", {
      timeZone: "Asia/Dhaka",
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      hour12: true,
    });

  const triggerLabel =
    triggerType === "voice"
      ? "Voice keyword activation ('সাহায্য করো')"
      : triggerType === "auto_stationary"
      ? "AI pattern detection — user stationary in danger zone for 10+ minutes"
      : "Manual SOS button press";

  const locationLines = (locationHistory || [])
    .slice(0, 10)
    .map(
      (loc, i) =>
        `  ${i + 1}. Lat: ${Number(loc.latitude).toFixed(5)}, Lng: ${Number(
          loc.longitude
        ).toFixed(5)} — ${new Date(
          loc.recorded_at
        ).toLocaleTimeString("en-BD", {
          timeZone: "Asia/Dhaka",
          hour12: true,
        })}`
    )
    .join("\n");

  const riskAssessment =
    riskScore >= 8
      ? "CRITICAL — Immediate police response recommended."
      : riskScore >= 5
      ? "HIGH — Area has elevated crime risk. Follow-up advised."
      : riskScore >= 3
      ? "MEDIUM — Moderate risk area. Situation monitoring recommended."
      : "LOW/UNKNOWN — Risk data unavailable or minimal.";

  return `NIRVAYA WOMEN SAFETY APP
OFFICIAL INCIDENT REPORT
${"─".repeat(40)}

REFERENCE ID: ${sosId}
GENERATED: ${formatTime(new Date().toISOString())}

${"─".repeat(40)}
1. INCIDENT SUMMARY
${"─".repeat(40)}
${userName || "Anonymous User"} triggered an emergency SOS alert via the Nirvaya Women Safety App. The incident occurred in ${district}, Bangladesh. The SOS was activated through ${triggerLabel} and remained active for ${durationMinutes} minute(s) before being resolved.

${"─".repeat(40)}
2. TIMELINE OF EVENTS
${"─".repeat(40)}
- SOS TRIGGERED:  ${formatTime(startTime)}
- SOS RESOLVED:   ${formatTime(endTime)}
- DURATION:       ${durationMinutes} minute(s)
- TRIGGER METHOD: ${triggerLabel}

${"─".repeat(40)}
3. LOCATION INFORMATION
${"─".repeat(40)}
District: ${district}, Bangladesh
Live tracking link: ${trackingLink || "N/A"}

Location history (up to 10 recorded points):
${locationLines || "  No location history recorded."}

${"─".repeat(40)}
4. AI RISK ASSESSMENT
${"─".repeat(40)}
Risk score at time of trigger: ${riskScore ?? "N/A"} / 10
Assessment: ${riskAssessment}

${"─".repeat(40)}
5. RECOMMENDED FOLLOW-UP ACTIONS
${"─".repeat(40)}
- Contact the user to confirm their safety and wellbeing.
- Review the location history for any signs of movement restriction.
- If risk score is HIGH or CRITICAL, consider filing a formal police report.
- Preserve this document as evidence if legal action is required.
- Share the live tracking link with local law enforcement if needed.

${"─".repeat(40)}
This report was auto-generated by Nirvaya Women Safety App.
${"─".repeat(40)}`;
};